# docker-compose.yml
version: "3"
services:
  webapp:
    depends_on:
      - database
    build:
      context: ./server
    ports:
      - "5100:3003"
  database:
    image: "postgres" # use latest official postgres version
    ports:
      - "5432:5432"
    env_file:
      - database.env # configure postgres
    volumes:
      - database-data:/var/lib/postgresql/data/ # persist data even if container shuts down
volumes:
  database-data: # named volumes can be managed easier using docker-compose
