# docker-compose-dev.yml
version: "3"
services:
  database:
    image: "postgres" # use latest official postgres version
    ports:
      - "5432:5432"
    env_file:
      - database.env # configure postgres
    volumes:
      - database-data-dev:/var/lib/postgresql/data/ # persist data even if container shuts down
      - ./postgresql-scripts-dev:/docker-entrypoint-initdb.d/ # mapping to intial sql scripts that should be run
volumes:
  database-data-dev: # named volumes can be managed easier using docker-compose
