# docker-compose.yml
version: "3"
services:
  webapp:
    depends_on:
      - databaseprod
    build:
      context: ./server
    ports:
      - "5100:3003"
  databaseprod:
    image: "postgres" # use latest official postgres version
    ports:
      - "5432:5432"
    env_file:
      - database.env # configure postgres
    volumes:
      - database-data:/var/lib/postgresql/data/ # persist data even if container shuts down
      - ./postgresql-scripts-prod:/docker-entrypoint-initdb.d/ # mapping to intial sql scripts that should be run
volumes:
  database-data: # named volumes can be managed easier using docker-compose
